# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EMATrike.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(873, 622)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(290, 210, 54, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(170, 210, 79, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.freq = QtWidgets.QLineEdit(Form)
        self.freq.setGeometry(QtCore.QRect(240, 100, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.freq.setFont(font)
        self.freq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.freq.setAlignment(QtCore.Qt.AlignCenter)
        self.freq.setObjectName("freq")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(110, 100, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(490, 170, 231, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(440, 210, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(580, 200, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(20, 250, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(20, 290, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(20, 330, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(140, 150, 61, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(70, 450, 181, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.sensor_crank = QtWidgets.QComboBox(Form)
        self.sensor_crank.setGeometry(QtCore.QRect(260, 450, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sensor_crank.setFont(font)
        self.sensor_crank.setObjectName("sensor_crank")
        self.sensor_crank.addItem("")
        self.sensor_crank.addItem("")
        self.sensor_crank.addItem("")
        self.sensor_crank.addItem("")
        self.sensor_crank.addItem("")
        self.sensor_crank.addItem("")
        self.sensor_crank.addItem("")
        self.sensor_crank.addItem("")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(70, 500, 181, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.sensor_remote_control = QtWidgets.QComboBox(Form)
        self.sensor_remote_control.setGeometry(QtCore.QRect(260, 500, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sensor_remote_control.setFont(font)
        self.sensor_remote_control.setObjectName("sensor_remote_control")
        self.sensor_remote_control.addItem("")
        self.sensor_remote_control.addItem("")
        self.sensor_remote_control.addItem("")
        self.sensor_remote_control.addItem("")
        self.sensor_remote_control.addItem("")
        self.sensor_remote_control.addItem("")
        self.sensor_remote_control.addItem("")
        self.sensor_remote_control.addItem("")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(380, 460, 221, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.serial_port_sensors = QtWidgets.QComboBox(Form)
        self.serial_port_sensors.setGeometry(QtCore.QRect(620, 460, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.serial_port_sensors.setFont(font)
        self.serial_port_sensors.setCurrentText("")
        self.serial_port_sensors.setObjectName("serial_port_sensors")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(380, 500, 221, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.serial_port_stimulator = QtWidgets.QComboBox(Form)
        self.serial_port_stimulator.setGeometry(QtCore.QRect(620, 500, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.serial_port_stimulator.setFont(font)
        self.serial_port_stimulator.setCurrentText("")
        self.serial_port_stimulator.setObjectName("serial_port_stimulator")
        self.button_start = QtWidgets.QPushButton(Form)
        self.button_start.setGeometry(QtCore.QRect(310, 550, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_start.setFont(font)
        self.button_start.setObjectName("button_start")
        self.current_less = QtWidgets.QPushButton(Form)
        self.current_less.setGeometry(QtCore.QRect(200, 380, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.current_less.setFont(font)
        self.current_less.setObjectName("current_less")
        self.current_plus = QtWidgets.QPushButton(Form)
        self.current_plus.setGeometry(QtCore.QRect(290, 380, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.current_plus.setFont(font)
        self.current_plus.setObjectName("current_plus")
        self.current_quad_right = QtWidgets.QSpinBox(Form)
        self.current_quad_right.setGeometry(QtCore.QRect(290, 250, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.current_quad_right.setFont(font)
        self.current_quad_right.setProperty("value", 60)
        self.current_quad_right.setObjectName("current_quad_right")
        self.current_quad_left = QtWidgets.QSpinBox(Form)
        self.current_quad_left.setEnabled(True)
        self.current_quad_left.setGeometry(QtCore.QRect(200, 250, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.current_quad_left.setFont(font)
        self.current_quad_left.setProperty("value", 60)
        self.current_quad_left.setObjectName("current_quad_left")
        self.current_post_left = QtWidgets.QSpinBox(Form)
        self.current_post_left.setGeometry(QtCore.QRect(200, 290, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.current_post_left.setFont(font)
        self.current_post_left.setProperty("value", 32)
        self.current_post_left.setObjectName("current_post_left")
        self.current_glut_left = QtWidgets.QSpinBox(Form)
        self.current_glut_left.setGeometry(QtCore.QRect(200, 330, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.current_glut_left.setFont(font)
        self.current_glut_left.setProperty("value", 58)
        self.current_glut_left.setObjectName("current_glut_left")
        self.current_post_right = QtWidgets.QSpinBox(Form)
        self.current_post_right.setGeometry(QtCore.QRect(290, 290, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.current_post_right.setFont(font)
        self.current_post_right.setProperty("value", 32)
        self.current_post_right.setObjectName("current_post_right")
        self.current_glut_right = QtWidgets.QSpinBox(Form)
        self.current_glut_right.setGeometry(QtCore.QRect(290, 330, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.current_glut_right.setFont(font)
        self.current_glut_right.setProperty("value", 58)
        self.current_glut_right.setObjectName("current_glut_right")
        self.cadence = QtWidgets.QSpinBox(Form)
        self.cadence.setEnabled(True)
        self.cadence.setGeometry(QtCore.QRect(240, 150, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cadence.setFont(font)
        self.cadence.setProperty("value", 50)
        self.cadence.setObjectName("cadence")
        self.ang_initial_post_left = QtWidgets.QSpinBox(Form)
        self.ang_initial_post_left.setGeometry(QtCore.QRect(480, 290, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ang_initial_post_left.setFont(font)
        self.ang_initial_post_left.setMinimum(1)
        self.ang_initial_post_left.setMaximum(359)
        self.ang_initial_post_left.setSingleStep(5)
        self.ang_initial_post_left.setProperty("value", 105)
        self.ang_initial_post_left.setObjectName("ang_initial_post_left")
        self.ang_range_post_left = QtWidgets.QSpinBox(Form)
        self.ang_range_post_left.setGeometry(QtCore.QRect(640, 290, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ang_range_post_left.setFont(font)
        self.ang_range_post_left.setMaximum(359)
        self.ang_range_post_left.setSingleStep(5)
        self.ang_range_post_left.setProperty("value", 80)
        self.ang_range_post_left.setObjectName("ang_range_post_left")
        self.ang_initial_glut_left = QtWidgets.QSpinBox(Form)
        self.ang_initial_glut_left.setGeometry(QtCore.QRect(480, 330, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ang_initial_glut_left.setFont(font)
        self.ang_initial_glut_left.setMaximum(359)
        self.ang_initial_glut_left.setSingleStep(5)
        self.ang_initial_glut_left.setProperty("value", 20)
        self.ang_initial_glut_left.setObjectName("ang_initial_glut_left")
        self.ang_range_glut_left = QtWidgets.QSpinBox(Form)
        self.ang_range_glut_left.setGeometry(QtCore.QRect(640, 330, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ang_range_glut_left.setFont(font)
        self.ang_range_glut_left.setMaximum(359)
        self.ang_range_glut_left.setSingleStep(5)
        self.ang_range_glut_left.setProperty("value", 80)
        self.ang_range_glut_left.setObjectName("ang_range_glut_left")
        self.ang_range_quad_left = QtWidgets.QSpinBox(Form)
        self.ang_range_quad_left.setGeometry(QtCore.QRect(640, 250, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ang_range_quad_left.setFont(font)
        self.ang_range_quad_left.setMaximum(359)
        self.ang_range_quad_left.setSingleStep(5)
        self.ang_range_quad_left.setProperty("value", 75)
        self.ang_range_quad_left.setObjectName("ang_range_quad_left")
        self.ang_initial_quad_left = QtWidgets.QSpinBox(Form)
        self.ang_initial_quad_left.setEnabled(True)
        self.ang_initial_quad_left.setGeometry(QtCore.QRect(480, 250, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ang_initial_quad_left.setFont(font)
        self.ang_initial_quad_left.setMinimum(0)
        self.ang_initial_quad_left.setMaximum(359)
        self.ang_initial_quad_left.setSingleStep(5)
        self.ang_initial_quad_left.setProperty("value", 250)
        self.ang_initial_quad_left.setObjectName("ang_initial_quad_left")
        self.angles_plus = QtWidgets.QPushButton(Form)
        self.angles_plus.setGeometry(QtCore.QRect(510, 380, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.angles_plus.setFont(font)
        self.angles_plus.setObjectName("angles_plus")
        self.angles_less = QtWidgets.QPushButton(Form)
        self.angles_less.setGeometry(QtCore.QRect(460, 380, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.angles_less.setFont(font)
        self.angles_less.setObjectName("angles_less")

        self.retranslateUi(Form)
        self.sensor_crank.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Direita"))
        self.label.setText(_translate("Form", "Esquerda"))
        self.freq.setText(_translate("Form", "50"))
        self.label_5.setText(_translate("Form", "Frequência"))
        self.label_6.setText(_translate("Form", "Ângulos (Perna esquerda)"))
        self.label_7.setText(_translate("Form", "Ângulo inicial"))
        self.label_8.setText(_translate("Form", "Janela de estimulação"))
        self.label_9.setText(_translate("Form", "Quadríceps"))
        self.label_10.setText(_translate("Form", "Posterior"))
        self.label_11.setText(_translate("Form", "Glúteos"))
        self.label_12.setText(_translate("Form", "RPM"))
        self.label_13.setText(_translate("Form", "Sensor da pedivela"))
        self.sensor_crank.setCurrentText(_translate("Form", "2"))
        self.sensor_crank.setItemText(0, _translate("Form", "0"))
        self.sensor_crank.setItemText(1, _translate("Form", "1"))
        self.sensor_crank.setItemText(2, _translate("Form", "2"))
        self.sensor_crank.setItemText(3, _translate("Form", "3"))
        self.sensor_crank.setItemText(4, _translate("Form", "4"))
        self.sensor_crank.setItemText(5, _translate("Form", "5"))
        self.sensor_crank.setItemText(6, _translate("Form", "6"))
        self.sensor_crank.setItemText(7, _translate("Form", "7"))
        self.label_14.setText(_translate("Form", "Controle remoto"))
        self.sensor_remote_control.setCurrentText(_translate("Form", "3"))
        self.sensor_remote_control.setItemText(0, _translate("Form", "0"))
        self.sensor_remote_control.setItemText(1, _translate("Form", "1"))
        self.sensor_remote_control.setItemText(2, _translate("Form", "2"))
        self.sensor_remote_control.setItemText(3, _translate("Form", "3"))
        self.sensor_remote_control.setItemText(4, _translate("Form", "4"))
        self.sensor_remote_control.setItemText(5, _translate("Form", "5"))
        self.sensor_remote_control.setItemText(6, _translate("Form", "6"))
        self.sensor_remote_control.setItemText(7, _translate("Form", "7"))
        self.label_15.setText(_translate("Form", "Porta serial das IMUs"))
        self.label_16.setText(_translate("Form", "Porta serial do estimulador"))
        self.button_start.setText(_translate("Form", "Start"))
        self.current_less.setText(_translate("Form", "-"))
        self.current_plus.setText(_translate("Form", "+"))
        self.angles_plus.setText(_translate("Form", "+"))
        self.angles_less.setText(_translate("Form", "-"))

